CREATE DATABASE DATA_REGISTER
GO

USE DATA_REGISTER
GO

drop table USER_PASWE
CREATE TABLE USER_PASWE (
	USERNAME VARCHAR(50) PRIMARY KEY,
	PASSW VARCHAR(50),
	ENCRYPT_PASSW VARCHAR(100),
	SALT VARCHAR(100)
)

DROP TABLE  UserLoginInfo
select *from USER_PASWE
select *from UserLoginInfo
CREATE TABLE  UserLoginInfo (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) NOT NULL,
    PASSW NVARCHAR(255) NOT NULL,
	ENCRYPT_PASSW VARCHAR(100) NOT NULL,
	SALT VARCHAR(100) NOT NULL,
    LastLogin DATETIME
	
);
